ALTER TABLE INFORMACAO_PAGAMENTO
ADD codigo_aluguel BIGINT(20) NOT NULL DEFAULT 1;

ALTER TABLE INFORMACAO_PAGAMENTO
ADD CONSTRAINT fk_aluguel_informacao_pagamento   FOREIGN KEY (codigo_aluguel) REFERENCES ALUGUEL(codigo);

