ALTER TABLE IMOVEL ADD  excluido BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE ALUGUEL ADD excluido BOOLEAN NOT NULL  DEFAULT FALSE;

ALTER TABLE INFORMACAO_PAGAMENTO ADD excluido BOOLEAN NOT NULL  DEFAULT FALSE;

ALTER TABLE GASTO_ADICIONAL ADD excluido BOOLEAN NOT NULL  DEFAULT FALSE;

ALTER TABLE locatario ADD excluido BOOLEAN NOT NULL  DEFAULT FALSE;

ALTER TABLE TEMPLATE_FORMA_PAGAMENTO ADD excluido BOOLEAN NOT NULL  DEFAULT FALSE;
